network.host: 0.0.0.0

discovery.type: single-node
bootstrap.memory_lock: true
action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*

# Cluster settings
# cluster.name: es-cluster
# cluster.initial_master_nodes: es01,es02,es03

### x-pack functions
# xpack.security.enabled: false
# xpack.monitoring.enabled: true
# xpack.graph.enabled: true
# xpack.watcher.enabled: false

# xpack.license.self_generated.type: trial
# xpack.security.enabled: true
# xpack.monitoring.collection.enabled: true